 고객 3,500명에 대한 학습용 데이터(y_train.csv, X_train.csv)를 이용하여 성별예측 모형을 만든
후, 이를 평가용 데이터(X_test.csv)에 적용하여 얻은 2,482명 고객의 성별 예측값(남자일 확률)을
다음과 같은 형식의 CSV 파일로 생성하시오.(제출한 모델의 성능은 ROC-AUC 평가지표에 따라
채점)

In [2]:
# !pip install sklearn

  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=615898fbc4de5ea9c620af99710df6d21da9cd04cc12e37e496ce9b855026f06
  Stored in directory: c:\users\stephen_covey\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


In [24]:
import os
import pandas as pd

x_train=pd.read_csv('X_train.csv',encoding='euc-kr')
y_train=pd.read_csv('y_train.csv',encoding='euc-kr')
x_test=pd.read_csv('X_test.csv',encoding='euc-kr')

x_train

cust_id       총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0           0   68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1           1    2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2           2    3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3           3   16077620   4935000        NaN      기타   광주점    18  2.444444   
4           4   29050000  24000000        NaN      보석  본  점     2  1.500000   
...       ...        ...       ...        ...     ...   ...   ...       ...   
3495     3495    3175200   3042900        NaN      골프  본  점     1  2.000000   
3496     3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000   
3497     3497      75000     75000        NaN    주방용품   창원점     1  1.000000   
3498     3498    1875000   1000000        NaN     화장품  본  점     2  1.000000   
3499     3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053   

        주말방문비율  구매주기  
0     0.527027    17  
1     0.000000     1  
2     0.000000     1  
3     0.318182    16  
4     0.000000    85  
...        ...   ...  
3495  1.000000     0  
3496  0.461538    40  
3497  0.000000     0  
3498  0.000000    39  
3499  0.467391     8  

[3500 rows x 10 columns]

In [25]:
y_train

cust_id  gender
0           0       0
1           1       0
2           2       1
3           3       1
4           4       0
...       ...     ...
3495     3495       1
3496     3496       1
3497     3497       0
3498     3498       0
3499     3499       0

[3500 rows x 2 columns]

In [26]:
x_test

cust_id       총구매액     최대구매액        환불금액   주구매상품 주구매지점  내점일수    내점당구매건수  \
0        3500   70900400  22000000   4050000.0      골프  부산본점    13   1.461538   
1        3501  310533100  38558000  48034700.0     농산물   잠실점    90   2.433333   
2        3502  305264140  14825000  30521000.0    가공식품  본  점   101  14.623762   
3        3503    7594080   5225000         NaN    주방용품  부산본점     5   2.000000   
4        3504    1795790   1411200         NaN     수산품  청량리점     3   2.666667   
...       ...        ...       ...         ...     ...   ...   ...        ...   
2477     5977   82581500  23976000         NaN      골프  부산본점     8   1.750000   
2478     5978     480000    480000         NaN    섬유잡화   광주점     1   1.000000   
2479     5979  260003790  25750000         NaN  남성 캐주얼  본  점    19   3.736842   
2480     5980   88991520  18120000         NaN      육류  본  점     5   3.600000   
2481     5981     623700    209000         NaN    가공식품  영등포점     2   5.000000   

        주말방문비율  구매주기  
0     0.789474    26  
1     0.369863     3  
2     0.083277     3  
3     0.000000    47  
4     0.125000     8  
...        ...   ...  
2477  0.642857    40  
2478  0.000000     0  
2479  0.915493    18  
2480  0.444444    60  
2481  0.000000    31  

[2482 rows x 10 columns]

## 1) 결측 데이터 처리

In [27]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cust_id  3500 non-null   int64  
 1   총구매액     3500 non-null   int64  
 2   최대구매액    3500 non-null   int64  
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   object 
 5   주구매지점    3500 non-null   object 
 6   내점일수     3500 non-null   int64  
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(5), object(2)
memory usage: 273.6+ KB


### 1-1. 결측치 제거




In [28]:
x_train = x_train.fillna(0)
x_test = x_test.fillna(0)
x_train

cust_id       총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0           0   68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1           1    2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2           2    3197000   1639000        0.0  남성 캐주얼   관악점     2  2.000000   
3           3   16077620   4935000        0.0      기타   광주점    18  2.444444   
4           4   29050000  24000000        0.0      보석  본  점     2  1.500000   
...       ...        ...       ...        ...     ...   ...   ...       ...   
3495     3495    3175200   3042900        0.0      골프  본  점     1  2.000000   
3496     3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000   
3497     3497      75000     75000        0.0    주방용품   창원점     1  1.000000   
3498     3498    1875000   1000000        0.0     화장품  본  점     2  1.000000   
3499     3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053   

        주말방문비율  구매주기  
0     0.527027    17  
1     0.000000     1  
2     0.000000     1  
3     0.318182    16  
4     0.000000    85  
...        ...   ...  
3495  1.000000     0  
3496  0.461538    40  
3497  0.000000     0  
3498  0.000000    39  
3499  0.467391     8  

[3500 rows x 10 columns]

### 1-2. 범주형변수 변환 (인코딩)

In [29]:
## Pandas의 factorize : sklearn의 라벨 인코딩과 유사 ( 빈도 순으로 인코딩 )

# pd.factorize(x_train["주구매상품"]) 의 결과는 factorize의 값([0])과 인덱스([1])가 나옴
# .reshape(-1,1)의 경우 행은 가변적, 열은 1행으로 도출 / 해당 분석에는 굳이 쓸 필요는 없는듯 (유무 상관없이 결과 같음)
x_train.loc[:, "주구매상품"] = pd.factorize(x_train["주구매상품"])[0].reshape(-1,1)
x_train.loc[:, "주구매지점"] = pd.factorize(x_train["주구매지점"])[0].reshape(-1,1)


x_test.loc[:, "주구매상품"] = pd.factorize(x_test["주구매상품"])[0].reshape(-1,1)
x_test.loc[:, "주구매지점"] = pd.factorize(x_test["주구매지점"])[0].reshape(-1,1)

# x_train['gender'] = y_train['gender'] # label을 트레이닝 데이터에 합침, 데이터 분리를 위해서.
x_train.head()

cust_id      총구매액     최대구매액       환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      0      0    19  3.894737   
1        1   2136000   2136000   300000.0      1      1     2  1.500000   
2        2   3197000   1639000        0.0      2      2     2  2.000000   
3        3  16077620   4935000        0.0      0      3    18  2.444444   
4        4  29050000  24000000        0.0      3      4     2  1.500000   

     주말방문비율  구매주기  
0  0.527027    17  
1  0.000000     1  
2  0.000000     1  
3  0.318182    16  
4  0.000000    85

In [30]:
# cust_id 열 제거 (아이디 삭제)
x_train = x_train.iloc[:, 1:]
y_train = y_train['gender']

x_test = x_test.iloc[:,1:] # 3500 ~ 5981

## 2) 데이터 스케일링

> * 이것은 엔지니어의 약속으로 변환을 하면 안된다. (비추천)

In [8]:
# 개념은 스케일러를 train에 맞춰두고 test에 그대로 진행
# 각자 진행하면 오류발생 (엄청난 영향을 준다.)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
# x_test_scaled[0]

## 3) 모델 만들기

- y값이 성별(0,1)이므로 이진분류로 결과를 낸다. 

In [9]:
# 선형 회귀 일 경우
# from sklearn.linear_model import LinearRegression

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt
import numpy as np

## 4) 훈련

In [11]:
def train_and_test(model):
    model.fit(x_train_scaled,y_train) # 훈련 세트(x_train)를 타겟값(y_train)에 대하여 학습
    prediction = model.predict(x_test_scaled) # 테스트(x_test) 데이터 세트에 대해 타겟값 예측
    
    # 선형회귀의 경우 proba가 없음
    predict_proba = model.predict_proba(x_test_scaled) # 각각의 결과값 도출
    print(predict_proba)
    
    accuracy = round(model.score(x_train_scaled,y_train) * 100, 2) # 10번 시행시 평균 정확도
    print("정확도 : ", accuracy, "%")
    return prediction

## 5) 예측 (해당 레이블로 분류될 확률 값을 알고 싶다)

In [12]:
log_pred = train_and_test(LogisticRegression())

[[0.60940661 0.39059339]
 [0.81758373 0.18241627]
 [0.84803216 0.15196784]
 ...
 [0.57936227 0.42063773]
 [0.54835089 0.45164911]
 [0.63201073 0.36798927]]
정확도 :  63.17 %


In [40]:
knn_pred = train_and_test(KNeighborsClassifier())

[[0.6 0.4]
 [0.8 0.2]
 [0.6 0.4]
 ...
 [0.6 0.4]
 [0.6 0.4]
 [0.4 0.6]]
정확도 :  73.6 %


In [43]:
rf_pred = train_and_test(RandomForestClassifier())

[[0.56 0.44]
 [0.77 0.23]
 [0.88 0.12]
 ...
 [0.52 0.48]
 [0.53 0.47]
 [0.52 0.48]]
정확도 :  99.91 %


In [23]:
# kernel : {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'}, default='rbf'
svm_pred = train_and_test(SVC(kernel='rbf', probability=True)) # 확률 옵션을 True로 줘야함

[[0.64115459 0.35884541]
 [0.66280042 0.33719958]
 [0.60577953 0.39422047]
 ...
 [0.4643529  0.5356471 ]
 [0.57078174 0.42921826]
 [0.65510557 0.34489443]]
정확도 :  64.6 %


In [38]:
help(SVC)

Help on class SVC in module sklearn.svm._classes:

class SVC(sklearn.svm._base.BaseSVC)
 |  SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
 |  
 |  C-Support Vector Classification.
 |  
 |  The implementation is based on libsvm. The fit time scales at least
 |  quadratically with the number of samples and may be impractical
 |  beyond tens of thousands of samples. For large datasets
 |  consider using :class:`~sklearn.svm.LinearSVC` or
 |  :class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
 |  :class:`~sklearn.kernel_approximation.Nystroem` transformer.
 |  
 |  The multiclass support is handled according to a one-vs-one scheme.
 |  
 |  For details on the precise mathematical formulation of the provided
 |  kernel functions and how `gamma`, `coef0` and `degree` affect each
 

In [37]:
# 위에서 아래로 붙이기
X_combined_std = np.vstack((x_train, x_test))
# 왼쪽에서 오른쪽으로 붙이기
y_combined = np.hstack((y_train, y_test))

svm = SVC(kernel='linear', C=1.0, random_state=1)
# svm.fit(X_train_std, y_train)
svm.fit(x_train_scaled,y_train)
plot_decision_regions(X_combined_std, 
                      y_combined,
                      classifier=svm, 
                      test_idx=range(105, 150))
plt.xlabel('petal length [standardized]')
plt.ylabel('petal width [standardized]')
plt.legend(loc='upper left')
plt.tight_layout()
plt.show()

NameError: name 'y_test' is not defined

In [13]:
submit.to_csv('submit.csv', index = False)

NameError: name 'submit' is not defined

In [17]:
model = LogisticRegression()
model.fit(x_train_scaled,y_train)
predict_proba = model.predict_proba(x_test_scaled)

# 앞은 0 뒤는 1일 확률
# 출력은 1로 진행한다.
predict_proba

array([[0.60940661, 0.39059339],
       [0.81758373, 0.18241627],
       [0.84803216, 0.15196784],
       ...,
       [0.57936227, 0.42063773],
       [0.54835089, 0.45164911],
       [0.63201073, 0.36798927]])

In [ ]:
# predict vs predict_proba : 하나의 샘플 vs 각각 모든 샘플
submit = pd.DataFrame(predict_proba[:,1],columns=['gender'])
submit

In [164]:
# 남자는 1
submit['cust_id']=pd.DataFrame(range(3500,5982))
submit = submit[['cust_id','gender']]
submit

cust_id    gender
0        3500  0.390593
1        3501  0.182416
2        3502  0.151968
3        3503  0.343334
4        3504  0.376241
...       ...       ...
2477     5977  0.380413
2478     5978  0.464845
2479     5979  0.420638
2480     5980  0.451649
2481     5981  0.367989

[2482 rows x 2 columns]